import { useEffect, useState } from "react";
import { Award, LockKeyhole, Sparkles, Trophy } from "lucide-react";
import { Link } from "react-router-dom";
import api from "../services/api";

export default function Achievements() {
  const [data, setData] = useState(null);
  useEffect(() => { api.get("/achievements").then(({ data }) => setData(data)).catch(() => setData({ badges: [], unlocked: 0, total: 0 })); }, []);
  if (!data) return <div className="py-20 text-center text-slate-500">Loading your achievements...</div>;
  const next = data.badges.find((badge) => !badge.unlocked);
  return <div className="mx-auto max-w-6xl space-y-7"><section className="overflow-hidden rounded-3xl bg-gradient-to-br from-amber-500 via-orange-500 to-rose-500 p-6 text-white shadow-xl sm:p-9"><div className="grid gap-6 md:grid-cols-[1fr_auto] md:items-center"><div><div className="flex items-center gap-2 text-white/80"><Trophy size={20}/><span className="text-sm font-bold tracking-wide">YOUR ACHIEVEMENTS</span></div><h1 className="mt-3 text-3xl font-extrabold sm:text-4xl">Every small win counts.</h1><p className="mt-3 max-w-xl leading-7 text-white/85">Keep learning, building, and showing up. Your activity across SkillTrack unlocks new milestones.</p></div><div className="rounded-3xl border border-white/20 bg-white/15 p-5 text-center backdrop-blur"><p className="text-4xl font-extrabold">{data.unlocked}<span className="text-xl text-white/70">/{data.total}</span></p><p className="mt-1 text-xs font-bold tracking-wide text-white/80">BADGES UNLOCKED</p></div></div></section>
    {next && <section className="card flex flex-wrap items-center justify-between gap-4 border-brand-100 bg-gradient-to-r from-brand-50 to-white p-5"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-white text-2xl shadow-sm">{next.icon}</div><div><p className="text-xs font-bold text-brand-600">NEXT MILESTONE</p><h2 className="mt-0.5 font-bold">{next.title}</h2><p className="text-sm text-slate-500">{next.description}</p></div></div><span className="rounded-full bg-white px-3 py-1.5 text-sm font-bold text-brand-700 shadow-sm">{next.value}/{next.target}</span></section>}
    <section><div className="mb-4 flex items-center gap-2"><Award className="text-brand-600" size={20}/><h2 className="section-title">Badge collection</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{data.badges.map((badge) => <article key={badge.id} className={`relative overflow-hidden rounded-2xl border p-5 transition ${badge.unlocked ? "border-amber-200 bg-gradient-to-br from-amber-50 to-white shadow-md" : "border-slate-200 bg-white opacity-80"}`}><div className="flex items-start justify-between"><div className={`grid h-12 w-12 place-items-center rounded-2xl text-2xl ${badge.unlocked ? "bg-white shadow-sm" : "bg-slate-100 grayscale"}`}>{badge.unlocked ? badge.icon : <LockKeyhole size={19} className="text-slate-400"/>}</div>{badge.unlocked && <Sparkles size={17} className="text-amber-500"/>}</div><h3 className="mt-4 font-bold">{badge.title}</h3><p className="mt-1 min-h-10 text-sm leading-5 text-slate-500">{badge.description}</p><div className="mt-4"><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${badge.unlocked ? "bg-gradient-to-r from-amber-400 to-orange-500" : "bg-slate-300"}`} style={{ width: `${badge.target ? badge.value / badge.target * 100 : 0}%` }}/></div><p className="mt-2 text-xs font-bold text-slate-500">{badge.unlocked ? "UNLOCKED" : `${badge.value} / ${badge.target}`}</p></div></article>)}</div></section><section className="card p-6 text-center"><h2 className="font-bold">Ready for your next badge?</h2><p className="mt-1 text-sm text-slate-500">A short study session, a note, or a quick challenge is enough to make progress.</p><div className="mt-4 flex flex-wrap justify-center gap-3"><Link className="btn-primary" to="/courses">Continue learning</Link><Link className="btn-secondary" to="/mind-gym">Open Mind Gym</Link></div></section></div>;
}
