import { useEffect, useState } from "react";
import { BarChart3, BookOpen, BriefcaseBusiness, CheckCircle2, Users } from "lucide-react";
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from "recharts";
import api from "../services/api";
import { StatCard } from "../components/ui";

export default function Admin() {
  const [stats,setStats]=useState(null);
  useEffect(()=>{api.get("/admin/stats").then(({data})=>setStats(data.stats))},[]);
  if(!stats)return <div className="py-20 text-center text-slate-500">Loading analytics...</div>;
  const colors=["#4f46e5", "#0d9488", "#f97316", "#db2777", "#64748b"];
  return <div className="space-y-7"><div><h1 className="section-title">Admin dashboard</h1><p className="mt-1 text-sm text-slate-500">High-level platform activity and learner outcomes.</p></div><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><StatCard label="Users" value={stats.users} icon={Users}/><StatCard label="Courses" value={stats.courses} icon={BookOpen}/><StatCard label="Enrollments" value={stats.enrollments} icon={BarChart3}/><StatCard label="Applications" value={stats.applications} icon={BriefcaseBusiness}/></div><div className="grid gap-5 lg:grid-cols-[.85fr_1.15fr]"><div className="card p-6"><div className="flex items-center gap-3"><div className="rounded-xl bg-emerald-50 p-2 text-emerald-600"><CheckCircle2 size={19}/></div><div><p className="text-sm font-semibold text-slate-500">Course completion rate</p><p className="text-3xl font-extrabold">{stats.completionRate}%</p></div></div><div className="mt-6 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-brand-500 to-mint" style={{width:`${stats.completionRate}%`}}/></div><p className="mt-3 text-sm text-slate-500">{stats.completedEnrollments} completed enrollment{stats.completedEnrollments!==1?"s":""} across the platform.</p></div><div className="card p-6"><div className="flex items-center justify-between"><div><h2 className="font-bold">Application pipeline</h2><p className="mt-1 text-sm text-slate-500">Current job-search stages</p></div></div><div className="mt-4 h-56">{stats.applicationsByStatus?.length ? <ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={stats.applicationsByStatus} dataKey="value" nameKey="name" innerRadius={55} outerRadius={82} paddingAngle={3}>{stats.applicationsByStatus.map((entry,index)=><Cell key={entry.name} fill={colors[index % colors.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer> : <div className="grid h-full place-items-center text-sm text-slate-500">No applications yet</div>}</div><div className="flex flex-wrap justify-center gap-x-4 gap-y-2">{stats.applicationsByStatus?.map((item,index)=><span key={item.name} className="flex items-center gap-1.5 text-xs font-medium text-slate-600"><i className="h-2 w-2 rounded-full" style={{background:colors[index % colors.length]}}/>{item.name} ({item.value})</span>)}</div></div></div></div>
}
